//
//  ThreadSummaryView.swift
//  Yaip
//
//  View for displaying AI-generated thread summaries
//

import SwiftUI

struct ThreadSummaryView: View {
    @ObservedObject var viewModel: AIFeaturesViewModel
    @Environment(\.dismiss) private var dismiss
    @State private var copiedToClipboard = false

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    // Header
                    HStack {
                        Image(systemName: "sparkles")
                            .font(.title2)
                            .foregroundStyle(.purple)

                        VStack(alignment: .leading, spacing: 4) {
                            Text("AI Summary")
                                .font(.title3)
                                .fontWeight(.bold)

                            if let summary = viewModel.currentSummary {
                                Text("Analyzed \(summary.messageCount) messages")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }

                        Spacer()
                    }
                    .padding()
                    .background(Color.purple.opacity(0.1))
                    .cornerRadius(12)

                    // Summary content
                    if viewModel.isLoadingSummary {
                        AILoadingView(
                            title: "Analyzing conversation",
                            subtitle: "AI is reading and summarizing messages..."
                        )
                        .padding(.vertical, 20)

                    } else if let summary = viewModel.currentSummary {
                        // Use Markdown rendering for rich formatting
                        VStack(alignment: .leading, spacing: 16) {
                            Text(summary.summary)
                                .font(.body)

                            // Metadata
                            Divider()

                            HStack {
                                Label {
                                    Text("Confidence: \(Int(summary.confidence * 100))%")
                                } icon: {
                                    Image(systemName: "checkmark.seal.fill")
                                        .foregroundStyle(.green)
                                }
                                .font(.caption)

                                Spacer()

                                Text(summary.timestamp.formatted(date: .abbreviated, time: .shortened))
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                        .padding()
                        .background(Color(.systemBackground))
                        .cornerRadius(12)
                        .shadow(radius: 2)

                    } else if let error = viewModel.summaryError {
                        AIErrorView(error: error) {
                            viewModel.summarizeThread()
                        }
                    }

                    // Actions
                    if viewModel.currentSummary != nil {
                        VStack(spacing: 12) {
                            Button {
                                shareSummary()
                            } label: {
                                Label("Share Summary", systemImage: "square.and.arrow.up")
                                    .frame(maxWidth: .infinity)
                            }
                            .buttonStyle(.bordered)

                            Button {
                                copySummaryToClipboard()
                            } label: {
                                Label(copiedToClipboard ? "Copied!" : "Copy to Clipboard", systemImage: copiedToClipboard ? "checkmark" : "doc.on.doc")
                                    .frame(maxWidth: .infinity)
                            }
                            .buttonStyle(.bordered)
                        }
                    }
                }
                .padding()
            }
            .navigationTitle("Summary")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                }
            }
        }
    }

    private func summaryText() -> String? {
        guard let summary = viewModel.currentSummary else { return nil }
        return """
        Thread Summary (\(summary.messageCount) messages)

        \(summary.summary)

        Generated by Yaip AI \u{2022} \(summary.timestamp.formatted())
        """
    }

    private func shareSummary() {
        guard let text = summaryText() else { return }

        let activityVC = UIActivityViewController(
            activityItems: [text],
            applicationActivities: nil
        )

        // Required for iPad: set popover source
        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let window = windowScene.windows.first,
           let rootVC = window.rootViewController {
            if let popover = activityVC.popoverPresentationController {
                popover.sourceView = window
                popover.sourceRect = CGRect(x: window.bounds.midX, y: window.bounds.midY, width: 0, height: 0)
                popover.permittedArrowDirections = []
            }
            rootVC.present(activityVC, animated: true)
        }
    }

    private func copySummaryToClipboard() {
        guard let text = summaryText() else { return }
        UIPasteboard.general.string = text
        copiedToClipboard = true

        Task {
            try? await Task.sleep(for: .seconds(2))
            copiedToClipboard = false
        }
    }
}

#Preview {
    ThreadSummaryView(viewModel: AIFeaturesViewModel(conversationID: "test-123"))
}
